# Generated by Django 5.0.1 on 2025-12-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('is_ended', models.BooleanField()),
                ('session_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('WHOLE_CLASS', 'Whole Class')], max_length=20)),
                ('subject_to_be_taught', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjectsmodel')),
                ('teacher', models.ManyToManyField(to='accounts.teachermodel')),
            ],
        ),
    ]
