# Generated by Django 5.0.1 on 2025-12-17 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('school_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admission_number', models.CharField(max_length=25, unique=True)),
                ('date_of_birth', models.DateField()),
                ('is_disabled', models.BooleanField(default=False)),
                ('disabilities', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('religion', models.CharField(choices=[('CHRISTIANITY', 'Christianity'), ('ISLAM', 'Islam'), ('OTHERS', 'Others')], max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='./student-img')),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='school_structure.studentclassmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('first_name', 'middle_name', 'last_name', 'email', 'admission_number')},
            },
        ),
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('reg_number', models.CharField(max_length=25, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('num_of_children', models.IntegerField()),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(choices=[('DR', 'Dr'), ('MR.', 'Mr'), ('MRS.', 'Mrs'), ('PROF.', 'Prof')], max_length=10)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(to='accounts.studentmodel')),
            ],
            options={
                'unique_together': {('first_name', 'middle_name', 'last_name', 'email', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('staff_number', models.CharField(max_length=25, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='school_structure.studentclassmodel')),
                ('classes_taught', models.ManyToManyField(related_name='classes', to='school_structure.studentclassmodel')),
                ('subjects_taught', models.ManyToManyField(to='academics.subjectsmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('first_name', 'middle_name', 'last_name', 'email', 'phone')},
            },
        ),
    ]
