# Generated by Django 5.0.1 on 2025-12-17 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('school_structure', '0003_alter_academictermmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='school_structure.studentclassmodel'),
        ),
    ]
