# Generated by Django 5.0.1 on 2025-12-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentmodel_current_class'),
        ('school_structure', '0004_alter_studentclassmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='current_class_arm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_structure.studentclassarmmodel'),
            preserve_default=False,
        ),
    ]
