# Generated by Django 5.0.1 on 2025-12-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentmodel_current_class_arm'),
        ('school_structure', '0004_alter_studentclassmodel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academicsessionmodel')),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academictermmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentmodel')),
            ],
        ),
    ]
