# Generated by Django 5.0.1 on 2025-12-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsessionmodel',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsessionmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academictermmodel',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclassarmmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclassarmmodel',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentclassmodel',
            name='arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arms', to='school_structure.studentclassarmmodel'),
        ),
        migrations.AlterField(
            model_name='studentclassmodel',
            name='klass_type',
            field=models.CharField(choices=[('CRECHE', 'Creche'), ('PRE-NURSERY', 'Pre Nursery'), ('NURSERY', 'Nursery'), ('PRIMARY', 'Primary'), ('JUNIOR-SECONDARY', 'Junior Secondary'), ('SENIOR-SECONDARY', 'Senior Secondary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentclasstypemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclasstypemodel',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
