# Generated by Django 5.0.1 on 2025-12-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0002_alter_academicsessionmodel_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academictermmodel',
            name='name',
            field=models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third'), ('FOURTH', 'Fourth')], max_length=15),
        ),
        migrations.AlterField(
            model_name='studentclassmodel',
            name='num_of_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
