# Generated by Django 5.0.1 on 2025-12-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0003_alter_academictermmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclassmodel',
            unique_together={('name', 'arm')},
        ),
    ]
