# Generated by Django 5.0.1 on 2025-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('creation_time', models.TimeField()),
                ('recipients', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_questions', models.IntegerField()),
                ('question', models.TextField()),
                ('submission_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('is_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricularEnrollmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('enrollment_date_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('regulations', models.TextField()),
                ('description', models.CharField(max_length=170)),
                ('person_in_charge', models.CharField(max_length=40)),
                ('is_free', models.BooleanField()),
                ('amount', models.IntegerField()),
                ('payment_structure', models.CharField(max_length=20, verbose_name=[('TERMLY', 'Termly'), ('SESSIONLY', 'Sessionly')])),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sub_code', models.CharField(max_length=10, unique=True)),
                ('num_of_students', models.IntegerField()),
                ('description', models.TextField()),
                ('pass_mark', models.IntegerField()),
            ],
        ),
    ]
