# Generated by Django 5.0.1 on 2025-12-17 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('school_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementmodel',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academicsessionmodel'),
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academictermmodel'),
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academicsessionmodel'),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academictermmodel'),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='classes_included',
            field=models.ManyToManyField(to='school_structure.studentclassmodel'),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teachermodel'),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extracurricularenrollmentmodel',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academicsessionmodel'),
        ),
        migrations.AddField(
            model_name='extracurricularenrollmentmodel',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academictermmodel'),
        ),
        migrations.AddField(
            model_name='extracurricularenrollmentmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='extracurricularmodel',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='extracurricularenrollmentmodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.extracurricularmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectsmodel',
            unique_together={('name', 'sub_code')},
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjectsmodel'),
        ),
    ]
