# Generated by Django 5.0.1 on 2025-12-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectsmodel',
            name='num_of_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
