# Generated by Django 5.0.1 on 2025-12-17 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('school_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('time_taken', models.TimeField()),
                ('report', models.JSONField()),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academictermmodel')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academicsessionmodel')),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.studentclassarmmodel')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.studentclassmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjectsmodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teachermodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subject', 'class_room', 'arm', 'date_taken')},
            },
        ),
        migrations.CreateModel(
            name='DayAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('time_taken', models.TimeField()),
                ('report', models.JSONField()),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academictermmodel')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.academicsessionmodel')),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.studentclassarmmodel')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.studentclassmodel')),
            ],
            options={
                'unique_together': {('class_room', 'arm', 'date_taken')},
            },
        ),
    ]
